[workspace]
members = [
	"all/lib/ArrayMath",
	
	"all/nodegraph/nodes/InstrumentNodes/InstrumentNodeLib",
	"all/nodegraph/nodes/InstrumentNodes/ChipInstrumentNode",
	"all/nodegraph/nodes/InstrumentNodes/SampledInstrumentNode",
	
	"all/nodegraph/nodes/MonoEchoNode",
	"all/nodegraph/nodes/VibratoNode",
]
resolver = "3"

[workspace.package]
name = "frusician-wasm-plugins"
version = "1.0.0"
edition = "2021"

description = "WebAssembly plugins for Frusician player. Necessary for audio playback to function properly."
repository = "https://github.com/charnam/frusician"
license = "AGPL-3.0-or-later"

[workspace.dependencies]
wasm-bindgen = "0.2.0"