[package]
name = "frusician-wasm-chipinstrumentnode"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen.workspace = true
frusician-wasm-instrumentnode-lib = { path = "../InstrumentNodeLib" }